config/routes.rb
Rails.application.routes.draw do
  root 'public#home'

  devise_for :users

  resources :items do
    member do
      put :answer
      put :reset_to_zero
      put :shift
    end

    collection do
      get :next
      get :search
      get :pending
      get :landing
      get :no_next
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  validate :at_least_one_text?

  scope :not_pending, -> { where('text_1 != ? and text_2 != ?', '', '') }
  scope :pending, -> { where('text_1 = ? or text_2 = ?', '', '') }

  belongs_to :user
  belongs_to :reverse_item, class_name: 'Item', foreign_key: 'reverse_item_id', optional: true

  after_update(:set_reverse_item_if_necessary)

  LEVEL_MAX = 4
  LEVEL_COUNT = LEVEL_MAX + 1

  LEVEL_DURATION = {
    0 => 1.day,
    1 => 1.day,
    2 => 7.days,
    3 => 30.days,
    4 => 180.days
  }

  def at_least_one_text?
    if text_1.blank? && text_2.blank?
      errors.add :base, "At least one text must be present"
    end
  end

  def set_level_regarding_answer(is_answer_correct)
    if is_answer_correct && level < LEVEL_MAX
      update level: level + 1
    elsif !is_answer_correct
      update level: 0
    end
  end

  def set_next_answer_at_after_answer
    self.next_answer_at = Date.today + LEVEL_DURATION[level]
  end

  def self.next
    items = self.to_show_today
    not_level_max_item_ids = items.where.not(level: LEVEL_MAX).ids
    items = items.where.not(level: LEVEL_MAX) if not_level_max_item_ids.size > 0
    items = items.order(Arel.sql('last_answer_at is not null, last_answer_at ASC'))
    items.first
  end

  def self.waiting_answer
    item_ids = where(next_answer_at: nil).or(Item.where('next_answer_at < ?', DateTime.now)).ids
    reverse_item_ids = Item.where(id: item_ids).pluck(:reverse_item_id)
    item_ids_to_exclude = Item.where(id: reverse_item_ids).where('last_answer_at >= ?', 3.days.ago.to_date).pluck(:reverse_item_id)
    Item.where(id: item_ids).where.not(id: item_ids_to_exclude).where.not(text_2: "")
  end

  def self.to_show_today
    items = waiting_answer
    item_ids = waiting_answer.ids
    item_ids_to_exclude = []

    items.pluck(:id, :reverse_item_id).each do |item_id, reverse_item_id|
      if !item_id.in?(item_ids_to_exclude) && reverse_item_id.in?(item_ids)
        item_ids_to_exclude << reverse_item_id
      end
    end

    items.where.not(id: item_ids_to_exclude)
  end

  def self.counts_by_level
    counts = group(:level).count.to_h

    LEVEL_COUNT.times.each_with_index do |index|
      counts[index] = 0 if !counts.has_key?(index)
    end

    counts
  end

  def create_with_reverse
    self.next_answer_at = DateTime.now + 1.day
    self.save

    if self.text_2.present?
      create_reverse_item
      return self.valid? && self.reverse_item.valid?
    else
      return self.valid?
    end
  end

  def create_reverse_item
    new_reverse_item = Item.create(text_1: self.text_2, text_2: self.text_1, user_id: self.user_id, next_answer_at: DateTime.now + 4.days, reverse_item: self)
    self.update(reverse_item: new_reverse_item)
  end

  def set_reverse_item_if_necessary
    if self.reverse_item.nil? && self.text_2.present?
      create_reverse_item
    end
  end

  def shift
    self.update last_answer_at: Date.today, next_answer_at: (Date.today + 3.days)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable, :trackable

  has_many :items

  def is_me?
    email == 'th.patris@gmail.com'
  end

  def counter
    self.items.to_show_today.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :redirect_root_domain
  before_action :authenticate_user!
  before_action :set_variables

  def set_variables
    return if current_user.nil?
    return if current_user.items.empty?

    @pending_count = current_user.items.pending.count
  end

  private

  def redirect_root_domain
    return unless request.host === 'vokab.io'
    redirect_to("#{request.protocol}www.vokab.io#{request.fullpath}", status: 301)
  end

  def after_sign_in_path_for(resource)
    next_items_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
    render :form
  end

  def show
    @item = current_user.items.find(params[:id])
  end

  def index
    @items = current_user.items.all
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.create_with_reverse
      flash[:notice] = "Item successfully created"
      redirect_to root_path
    else
      flash[:danger] = helpers.model_errors_as_html(@item)
      redirect_to new_item_path
    end
  end

  def edit
    @item = current_user.items.find(params[:id])

    render :form
  end

  def update
    @item = current_user.items.find(params[:id])

    if @item.update(item_params)
      flash[:success] = "Item successfully updated"
    else
      flash[:error] = "An error occured"
    end

    redirect_to item_path(@item)
  end

  def destroy
    @item = current_user.items.find(params[:id])

    if @item.destroy
      flash[:success] = "Item successfully deleted"
    else
      flash[:error] = "An error occured"
    end

    redirect_to root_path
  end

  def next
    next_item = current_user.items.next

    if next_item
      redirect_to item_path(next_item)
    else
      redirect_to no_next_items_path
    end
  end

  def no_next
  end

  def search
    sql_query = params[:query].downcase
    @items = current_user.items.where('lower(text_1) like ? or lower(text_2) like ?', "%#{sql_query}%", "%#{sql_query}%")

    if @items.size > 0
      flash.clear
      render :index
    else
      flash[:error] = "No results found for your search."
      @item = Item.new(text_1: params[:query])
      render :form
    end
  end

  def pending
    @items = current_user.items.pending
    render :index
  end

  def answer
    @item = current_user.items.find(params[:id])
    is_answer_correct = params[:is_answer_correct] == "true"
    @item.set_level_regarding_answer(is_answer_correct)
    @item.set_next_answer_at_after_answer
    @item.last_answer_at = Date.today

    if @item.save
      if is_answer_correct
        flash[:success] = "Well done!"
      else
        flash[:success] = "Maybe next time!"
      end
    else
      flash[:error] = "An error occured"
    end

    redirect_to next_items_path
  end

  def landing
    @counts_by_level = current_user.items.counts_by_level
    @counts_waiting_answer_by_level = current_user.items.to_show_today.counts_by_level
  end

  def reset_to_zero
    @item = current_user.items.find(params[:id])
    @item.update level: 0
    @item.save

    redirect_to item_path(@item)
  end

  def shift
    @item = current_user.items.find(params[:id])
    @item.shift

    redirect_to next_items_path
  end

  private

  def item_params
    params.require(:item).permit(:text_1, :text_2)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    redirect_to landing_items_path if user_signed_in?

    @page_title       = 'Never forget your vocabulary again'
    @page_description = 'Use Vokab to memorize faster and longer your new vocabulary. Enjoy, it is 100% free :)'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/items/form.html.erb
<div id="page-new-item" data-controller="dictionaries">
  <div class="card text-bg-light mt-4">
    <div class="card-body">
      <%= form_with model: @item, local: true do |form| %>
        <div class="mb-3">
          <%= form.text_area :text_1, class: 'form-control', tabindex: 1, data: { controller: "textarea-autogrow", "dictionaries-target": "textareaTop" }, placeholder: "Text to translate" %>
        </div>

        <% if current_user.is_me? %>
          <div class="dropdown d-grid mb-3">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
              Translate with
            </button>

            <ul class="dropdown-menu w-100">
              <% ["WordReference", "Linguee", "Deepl"].each do |dictionary| %>
                <li>
                  <a class="dropdown-item" data-dictionaries-target="dictionaryLink" data-action="dictionaries#goTo" data-dictionary="<%= dictionary %>">
                    <%= dictionary %>
                  </a>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.text_area :text_2, class: 'form-control', tabindex: 2, data: { controller: "textarea-autogrow", "dictionaries-target": "textareaTop" }, placeholder: "Translation" %>
        </div>

        <div class="d-grid">
          <%= form.submit "Save", class: "btn btn-primary" %>
        </div>

        <% if current_user.items.count > 0 %>
          <div class="d-grid mt-3">
            <%= link_to "Cancel", root_path, class: "btn btn-secondary" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<% @items.each do |item| %>
  <div class="row mb-3">
    <div class="col">
      <div class="card">
        <%= link_to item_path(item, no_quiz: true), class: "stretched-link text-reset text-decoration-none" do %>
          <div class="card-body">
            <p><%== item.text_1.blank? ? "&nbsp;" : item.text_1 %></p>
            <hr/>
            <p><%== item.text_2.blank? ? "&nbsp;" : item.text_2 %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/landing.html.erb
<div id="page-landing" class="center-align">
  <div class="d-grid">
    <%= link_to "Start", next_items_path, class: "btn btn-lg btn-primary mb-3" %>
  </div>

  <div class="row">
    <div class="col s12 m6 offset-m3">
      <% Item::LEVEL_COUNT.times.each do |level| %>
        <div class="text-bg-light text-start mb-3 p-2 rounded">
          Level <%= level %>

          <span class="badge text-bg-success">
            <%= @counts_waiting_answer_by_level[level] %> left today
          </span>

          <span class="badge text-bg-danger text-end float-end">
            <%= @counts_by_level[level] %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/no_next.html.erb
No more items to test for today :)

app/views/items/show.html.erb
<div id="page-show-item" data-controller="quizz">
  <div class="row">
    <div class="col s12">
      <div class="card">
        <div class="card-body" data-quizz-target="text1">
          <%= @item.text_1 %>
        </div>

        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning">
          <%= @item.level %>
        </span>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col s12">
      <div class="card">
        <div class="card-body text-white" data-quizz-target="text2">
          <%= @item.text_2 %>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col s12 d-flex">
      <% unless params[:no_quiz].present? %>
        <%= button_tag(type: 'button', class: "btn btn-primary", data: { "quizz-target": "showAnswerButton", action: "quizz#showAnswer" }) do %>
          <i class="bi-eye"></i> Show
        <% end %>

        <div data-quizz-target="answerButtons" class="d-none">
          <%= link_to(answer_item_path(@item, is_answer_correct: true), type: 'button', class: "btn btn-success", data: {turbo_method: "put", disable_with: '...'}) do %>
            <i class="bi-hand-thumbs-up"></i>
          <% end %>

          <%= link_to(answer_item_path(@item, is_answer_correct: false), type: 'button', class: "btn btn-danger", data: {turbo_method: "put", disable_with: '...'}) do %>
            <i class="bi-hand-thumbs-down"></i>
          <% end %>
        </div>
      <% end %>

      <div class="dropdown ms-auto">
        <button class="btn btn-secondary" type="button" data-bs-toggle="dropdown">
          <i class="bi-three-dots-vertical"></i>
        </button>

        <ul class="dropdown-menu">
          <li>
            <%= link_to(edit_item_path(@item), class: "dropdown-item") do %>
              <i class="bi-pencil"></i> Edit
            <% end %>
          </li>

          <li>
            <%= link_to("https://translate.google.com/?sl=en&tl=fr&op=translate&text=#{CGI.escape(@item.text_1)}", target: "_blank", class: "dropdown-item") do %>
              <i class="bi-chat-quote"></i> Pronunciation of top text
            <% end %>
          </li>

          <li>
            <%= link_to("https://translate.google.com/?sl=en&tl=fr&op=translate&text=#{CGI.escape(@item.text_2)}", target: "_blank", class: "dropdown-item") do %>
              <i class="bi-chat-quote"></i> Pronunciation of bottom text
            <% end %>
          </li>

          <li>
            <%= link_to(reset_to_zero_item_path(@item), data: {turbo_method: "put"}, class: "dropdown-item") do %>
              <i class="bi-arrow-clockwise"></i> Reset to level 0
            <% end %>
          </li>

          <li>
            <%= link_to(shift_item_path(@item), data: {turbo_method: "put"}, class: "dropdown-item") do %>
              <i class="bi-fast-forward"></i> Shift
            <% end %>
          </li>

          <li>
            <%= link_to(item_path(@item), data: {turbo_method: "delete"}, class: "dropdown-item") do %>
              <i class="bi-trash"></i> Delete
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_cookieconsent_init.html.erb
<script>
  $(function() {
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#e8eaf6",
          "text": "black"
        },
        "button": {
          "background": "#4b81e8"
        }
      }
    });
  })
</script>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <%
    if flash[:success] || flash[:notice]
      classes = 'green accent-4'
      message = flash[:success] || flash[:notice]
    elsif flash[:error] || flash[:alert]
      classes = 'red darken-1'
      message = flash[:error] || flash[:alert]
    end
  %>

  <script>
    $(function() {
      M.toast({
        html: '<%== message %>',
        classes: '<%= classes %>'
      })
    })
  </script>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-success text-start" role="alert">
    <%= notice %>
  </div>
<% end  %>

<% if alert.present? %>
  <div class="alert alert-danger text-start" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer indigo lighten-5">
  <div class="footer-copyright">
    <div class="container center-align">
      <a class="black-text" href="mailto: contact@vokab.io" target="_blank">Contact</a>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<%= render 'layouts/google_analytics' %>

<%= display_meta_tags site: 'Vokab' %>

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

<%= stylesheet_link_tag 'application', media: 'all' %>
<%= javascript_include_tag "application", "data-turbo-track": "reload" %>

<script data-ad-client="ca-pub-4660007325519303" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

<%= render 'layouts/cookieconsent_init' %>

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="#none" data-target="slide-menu" class="sidenav-trigger">
      <i class="material-icons">menu</i>
    </a>

    <a href="/" class="brand-logo center">VOKAB</a>

    <% if current_user.is_me? %>
      <div id="not_known_counter" class="custom-badge red right">
        <%= current_user.counter %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/_search_modal.html.erb
<div id="search-modal" class="modal">
  <div class="modal-content">
    <%= form_with url: search_items_path, method: :get, local: true do |form| %>
      <div class="input-field">
        <i class="material-icons prefix">search</i>
        <%= form.text_field :query %>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(function() {
    $('#search-modal').modal({
      onOpenEnd: function() {
        var side_menu = M.Sidenav.getInstance($('.sidenav'));
        side_menu.close();

        $("#search-modal form input#query").focus();
      }
    });
  });
</script>

app/views/layouts/_side_menu.html.erb
<ul id="slide-menu" class="sidenav sidenav-fixed indigo lighten-5">
  <li>
    <a href="/" class="brand-logo">Vokab</a>

    <% if current_user.is_me? %>
      <div id="not_known_counter" class="custom-badge red right hide-on-med-and-down">
        <%= current_user.counter %>
      </div>
    <% end %>
  </li>

  <li>
    <a href="<%= new_item_path %>">
      <i class="material-icons">add_circle</i>Add
    </a>
  </li>

  <li>
    <a href="#search-modal" class="modal-trigger">
      <i class="material-icons">search</i>Search
    </a>
  </li>

  <li>
    <%= link_to pending_items_path do %>
      Pending

      <% if @pending_count > 0 %>
        <span class="new badge red"><%= @pending_count %></span>
      <% end %>
    <% end %>
  </li>

  <li>
    <%= link_to "Edit profile", edit_user_registration_path %>
  </li>

  <li>
    <%= link_to "Contact", "mailto: contact@vokab.io", target: '_blank' %>
  </li>

  <li>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  </li>

  <% if current_user.is_admin? %>
    <li>
      <%= link_to "Database", '/rails/db', target: '_blank' %>
    </li>
  <% end %>
</ul>

<script>
  $(function() {
    $('.sidenav').sidenav();
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vokab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-dark">
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Vokab</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Add", new_item_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to pending_items_path, class: "nav-link" do %>
                Pending

                <% if @pending_count > 0 %>
                  <span class="badge bg-danger"><%= @pending_count %></span>
                <% end %>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link" %>
            </li>

            <li>
              <%= link_to "Contact", "mailto: contact@vokab.io", target: '_blank', class: "nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link" %>
            </li>

            <% if current_user.is_admin? %>
              <li>
                <%= link_to "Database", '/rails/db', target: '_blank', class: "nav-link" %>
              </li>
            <% end %>
          </ul>

          <%= form_with url: search_items_path, method: :get, class: "d-flex", local: true do |form| %>
            <%= form.text_field :query, class: "form-control me-2", type: "search", placeholder: "Search" %>

            <%= button_tag class: "btn btn-primary" do %>
              <i class="bi-search"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container text-center">
      <div class="mt-3">
        <%= render "layouts/flash_messages" %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vokab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-dark text-white">
    <div class="container text-center text-black">
      <div class="row">
        <div class="col-sm-6 mx-auto">
          <h1 class="mt-4 mb-4">
            <a href="/" class="text-white text-decoration-none">
              VOKAB
            </a>
          </h1>

          <div class="card">
            <div class="card-body">
              <%= render "layouts/flash_messages" %>

              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Vokab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-dark text-white">
    <div class="container text-center">
      <%= yield %>
    </div>
  </body>
</html>